---
title: Lo standby a freddo genera "Il record DataStoreException non esiste"
description: Descrizione
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '311'
ht-degree: 0%

---

# Lo standby a freddo genera &quot;Il record DataStoreException non esiste&quot;

## Descrizione


<b>Problema:</b>
Standby a freddo con file dedicato Datastore lancia un avviso su blobid mancante come quello a 1.

<b>Dettagli:</b>
Questo è solo un avviso, non un errore. Viene dal fatto che il datastore non ha modo di verificare se un binario esiste localmente, tranne che provando a caricare blob id.
Se l’id viene caricato, i registri non mostrano questo avviso. Tuttavia, se non viene trovato, lo standby sa che deve sincronizzarlo, quindi viene visualizzato l&#39;avviso 1 nei log.


1: *\*WARN\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Errore durante il caricamento di byte dal vapore durante il recupero per id f68a92b34779bbd194184251ec911 6370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b3477bbd194184251ec916370f3ebd301d6e32a8980aad070d57a188 45 non esiste
<br>    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Causato da: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 inesistente
<br>    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Risoluzione


Funziona come progettato e non indica un problema con il File DataStore.

<b>Per confermare:</b>

- Esempio di blob id mancante nei log: &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c22 0&quot;
- Per questo blob id, l&#39;indirizzo del filesystem deve essere: &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c 49c20&quot;
- Cerca il filesystem nell&#39;istanza standy e controlla se il file denominato è presente nel datastore.
- All&#39;interno di /repository/datastore, utilizza il comando di elenco (ls -ald): &quot;ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f193 5a2c49c20&quot;
- Dovresti essere in grado di visualizzare il file e confermare che l’ID BLOB non è in realtà mancante
